version: '3.8'

services:

  # Database for Transactions
  postgres:
    image: postgres:16
    container_name: aegis-postgres
    environment:
      POSTGRES_USER: aegis
      POSTGRES_PASSWORD: aegis
      POSTGRES_DB: aegis_transaction
    ports:
      - 5432:5432
    networks:
      - aegis-network
  
  # Fast Cache for Fraud Rules
  redis:
    image: redis:7-alpine
    container_name: aegis-redis
    ports:
      - 6379:6379
    networks:
      - aegis-network
  
  # Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: aegis-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - aegis-network
  
  # Message Broker (Kafka)
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: aegis-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - aegis-network

networks:
  aegis-network:
    driver: bridge